language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.1
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-4.9
      - g++-4.9
      - oracle-java8-installer
before_install:
  - export CXX="g++-4.9"
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - wget http://www.apache.org/dyn/closer.lua/cassandra/$CVER/apache-cassandra-$CVER-bin.tar.gz && tar -xvzf apache-cassandra-$CVER.tar.gz
  - sudo sh ./apache-cassandra-$CVER/bin/cassandra -R
  - sleep 20
install:
  - "MIX_ENV=test mix do local.hex --force, local.rebar --force, deps.get"
script:
  - "MIX_ENV=test mix do espec, coveralls.travis"
env:
  - CVER=3.9
notifications:
  recipients:
    - pavel@tatarsky.ru
